[package]
name = "Hively"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
minimax = "0.5.4"
strum = "0.27.2"
strum_macros = "0.27.2"
thiserror = "2.0.17"

[dev-dependencies]
pretty_assertions = "1.4.1"
